[package]
name = "slice_wav"
authors = ["Akiyuki Okayasu"]
description = "Export sliced wav files."
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
hound = "3.5.0"
